apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nginx-ingressroute
  namespace: nginx
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`nginx.tomkor.net`)
    kind: Rule
    services:
    - name: nginx
      port: 80